spring:
  application:
     name: web-service
eureka:
  client:
    registerWithEureka: true
    registryFetchIntervalSeconds: 10
pivotal:
  summary:
    quotes: 3
    symbols:
      #it: EMC,ORCL,IBM,INTC,AMD,HPQ,CSCO,AAPL
      it: EMC,ORCL,IBM,INTC
      fs: JPM,MS,BAC,GS,WFC,BK
